export enum Permission {
  READ_TEAMS = 'read:teams',
  MANAGE_TEAMS = 'manage:teams',
  VALIDATE_CONTROLE_TECHNIQUE = 'validate:controle_technique',
  READ_SCORES = 'read:scores',
  CREATE_SCORES = 'create:scores',
  UPDATE_OWN_SCORES = 'update:own_scores',
  READ_PLANNING = 'read:planning',
  MANAGE_PLANNING = 'manage:planning',
  READ_MATCHS = 'read:matchs',
  MANAGE_MATCHS = 'manage:matchs',
  CREATE_RENCONTRE = 'create:rencontre',
  READ_CLASSEMENTS = 'read:classements',
  READ_USERS = 'read:users',
  MANAGE_OWN_PROFILE = 'manage:own_profile',
  MANAGE_ALL_PROFILES = 'manage:all_profiles',
  DELETE_PROFILE = 'delete:profile',
}
